# Generated by Django 5.0.13 on 2025-12-03 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('veterinaria', '0002_cita_historialmedico'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historialmedico',
            name='id_mascota',
        ),
        migrations.DeleteModel(
            name='Cita',
        ),
        migrations.DeleteModel(
            name='HistorialMedico',
        ),
    ]
