# Generated by Django 5.0.13 on 2025-11-28 20:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dueño',
            fields=[
                ('id_dueño', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('direccion', models.CharField(max_length=255)),
                ('email', models.CharField(max_length=100)),
                ('fecha_registro', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Veterinario',
            fields=[
                ('id_veterinario', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especialidad', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('email', models.CharField(max_length=100)),
                ('num_colegiado', models.CharField(max_length=50)),
                ('turno', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mascota',
            fields=[
                ('id_mascota', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('especie', models.CharField(max_length=50)),
                ('raza', models.CharField(max_length=50)),
                ('edad', models.IntegerField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('sexo', models.CharField(max_length=1)),
                ('id_dueño', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.dueño')),
            ],
        ),
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id_vacuna', models.AutoField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=100)),
                ('tipo', models.CharField(max_length=50)),
                ('fecha_aplicacion', models.DateField()),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
            ],
        ),
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id_consulta', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_consulta', models.DateField()),
                ('motivo', models.TextField()),
                ('diagnostico', models.TextField()),
                ('tratamiento', models.TextField()),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('id_mascota', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.mascota')),
                ('id_veterinario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='veterinaria.veterinario')),
            ],
        ),
    ]
