from django.urls import path
from . import views

urlpatterns = [
    path('', views.inicio_Veterinaria, name='inicio_Veterinaria'),
    path('agregar_dueño/', views.agregar_dueño, name='agregar_dueño'),
    path('ver_dueños/', views.ver_dueños, name='ver_dueños'),
    path('actualizar_dueño/<int:id_dueño>/', views.actualizar_dueño, name='actualizar_dueño'),
    path('realizar_actualizacion_dueño/<int:id_dueño>/', views.realizar_actualizacion_dueño, name='realizar_actualizacion_dueño'),
    path('borrar_dueño/<int:id_dueño>/', views.borrar_dueño, name='borrar_dueño'),
    path('agregar_mascota/', views.agregar_mascota, name='agregar_mascota'),
    path('ver_mascotas/', views.ver_mascotas, name='ver_mascotas'),
    path('actualizar_mascota/<int:id_mascota>/', views.actualizar_mascota, name='actualizar_mascota'),
    path('realizar_actualizacion_mascota/<int:id_mascota>/', views.realizar_actualizacion_mascota, name='realizar_actualizacion_mascota'),
    path('borrar_mascota/<int:id_mascota>/', views.borrar_mascota, name='borrar_mascota'),
    path('agregar_veterinario/', views.agregar_veterinario, name='agregar_veterinario'),
    path('ver_veterinarios/', views.ver_veterinarios, name='ver_veterinarios'),
    path('actualizar_veterinario/<int:id_veterinario>/', views.actualizar_veterinario, name='actualizar_veterinario'),
    path('realizar_actualizacion_veterinario/<int:id_veterinario>/', views.realizar_actualizacion_veterinario, name='realizar_actualizacion_veterinario'),
    path('borrar_veterinario/<int:id_veterinario>/', views.borrar_veterinario, name='borrar_veterinario'),
    path('agregar_consulta/', views.agregar_consulta, name='agregar_consulta'),
    path('ver_consultas/', views.ver_consultas, name='ver_consultas'),
    path('actualizar_consulta/<int:id_consulta>/', views.actualizar_consulta, name='actualizar_consulta'),
    path('realizar_actualizacion_consulta/<int:id_consulta>/', views.realizar_actualizacion_consulta, name='realizar_actualizacion_consulta'),
    path('borrar_consulta/<int:id_consulta>/', views.borrar_consulta, name='borrar_consulta'),
    path('agregar_vacuna/', views.agregar_vacuna, name='agregar_vacuna'),
    path('ver_vacunas/', views.ver_vacunas, name='ver_vacunas'),
    path('actualizar_vacuna/<int:id_vacuna>/', views.actualizar_vacuna, name='actualizar_vacuna'),
    path('realizar_actualizacion_vacuna/<int:id_vacuna>/', views.realizar_actualizacion_vacuna, name='realizar_actualizacion_vacuna'),
    path('borrar_vacuna/<int:id_vacuna>/', views.borrar_vacuna, name='borrar_vacuna'),
]
